const LEVER_COMPANIES = {
  addepar: 'Addepar',
  blendlabs: 'Blend Labs',
  buildzoom: 'BuildZoom',
  yelp: 'Yelp',
  duolingo: 'Duolingo',
  netflix: 'Netflix',
  reddit: 'Reddit',
  plaid: 'Plaid',
  essential: 'Essential Products',
  lyft: 'Lyft',
  twitch: 'Twitch',
  nurx: 'Nurx',
  area1security: 'Area 1 Security',
  skillshare: 'Skillshare',
  socialtables: 'Social Tables',
  nava: 'Nava',
  kensho: 'Kensho',
  upside: 'Upside',
  etsy: 'Etsy',
  1776: '1776',
  neuralink: 'Neuralink',
  opendoor: 'Opendoor',
  snowflake: 'Snowflake',
  drawbridge: 'Drawbridge',
  coursera: 'Coursera',
  shopify: 'Shopify',
  affirm: 'Affirm',
  wish: 'Wish',
  wealthfront: 'Wealthfront',
  tyro: 'Tyro',
  intercom: 'Intercom',
  convoy: 'Convoy',
  axon: 'Axon',
  'indiegogo.com': 'Indiegogo',
  stellar: 'Stellar',
  databricks: 'Databricks',
  bluelabs: 'Blue Labs',
  shift: 'Shift',
  quora: 'Quora',
  karat: 'Karat',
  houzz: 'Houzz',
  palantir: 'Palantir',
  gigster: 'Gigster',
  livongo: 'Livongo',
  shapesecurity: 'Shape Security',
  zumper: 'Zumper',
};

const GREENHOUSE_COMPANIES = {
  yext: 'Yext',
  appian: 'Appian',
  airbnb: 'Airbnb',
  nextdoor: 'Nextdoor',
  coinbase: 'Coinbase',
  segment: 'Segment',
  comprehend: 'Comprehend',
  asana: 'Asana',
  squarespace: 'Squarespace',
  trialspark: 'Trialspark',
  leanplum: 'Leanplum',
  brave: 'Brave',
  nuna: 'Nuna Health',
  bluebeam: 'Bluebeam',
  datadog: 'Datadog',
  boxinc: 'Box',
  betterment: 'Betterment',
  jumptrading: 'Jump Trading',
  akunacapital: 'Akuna Capital',
  buzzfeed: 'Buzzfeed',
  joinhandshake: 'Handshake',
  fin: 'Fin',
  helix: 'Helix',
  casper: 'Casper',
  slack: 'Slack',
  stripe: 'Stripe',
  pinterest: 'Pinterest',
  khanacademy: 'Khan Academy',
  mealpal: 'Mealpal',
  classy: 'Classy',
  hyperlooptechnologies: 'Hyperloop One',
  digitalocean98: 'DigitalOcean',
  mark43: 'Mark43',
  endurance: 'Endurance',
  vaticlabs: 'Vatic Labs',
  foursquare26: 'Foursquare',
  urbancompass: 'Compass',
  quorum: 'Quorum Analytics',
  towerresearchcapital: 'Tower Research Capital',
  fitbit92: 'Fitbit',
  peak6: 'PEAK6',
  better: 'Better',
  spring: 'Spring',
  oscar: 'Oscar Health',
  tumblr: 'Tumblr',
  cadre: 'Cadre',
  mongoDB: 'MongoDB',
  flatironhealth: 'Flatiron Health',
  commonbond: 'Commonbond',
  knotch: 'Knotch',
  warbyparker: 'Warby Parker',
  uptake: 'Uptake',
  purestorage: 'Pure Storage',
  chanzuckerberginitiative: 'Chan Zuckerberg Initiative',
  tripadvisor: 'TripAdvisor',
  twilio: 'Twilio',
  everwise: 'Everwise',
  thumbtack: 'Thumbtack',
  imoim: 'imo.im',
  seatgeek: 'SeatGeek',
  snapchat: 'Snap Inc.',
  wehrtyou: 'Hudson River Trading',
  unity3d: 'Unity',
  timeinc: 'Time',
  rapid7: 'Rapid7',
  riotgames: 'Riot Games',
  qualtrics: 'Qualtrics',
  mapbox: 'Mapbox',
  instacart: 'Instacart',
  robinhood: 'Robinhood',
  checkr: 'Checkr',
  rubrik: 'Rubrik',
  figma: 'Figma',
  gusto: 'Gusto',
};

module.exports = {
  LEVER_COMPANIES,
  GREENHOUSE_COMPANIES,
};
